application: your-app-id
version: 1
runtime: python
api_version: 1

handlers:
- url: /content_manager.*
  script: main.py
  login: admin

- url: /content_lister.*
  script: main.py
  login: admin
  
- url: /.*
  script: main.py
